//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessControl.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Foto
    {
        public int Id { get; set; }
        public long Rfid { get; set; }

        [Remote("Cadastrar", "Cadastro", ErrorMessage = "É importante que você insira uma foto!")]
        public byte[] Imagem { get; set; }
    }
}
