//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessControl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Usuario
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe seu nome. Não precisa ser completo!")]
        public string Nome { get; set; }

        [Remote("EmailUnico", "Cadastro", ErrorMessage = "Alguém já está usando este e-mail!")]
        [Required(ErrorMessage = "Informe seu e-mail, nos ajudará a entrar em contato com você!")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "O E-mail informado não é válido!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Por favor, descreva-se. Isso nos ajudará a conhecer melhor você!")]
        [StringLength(200, MinimumLength = 10, ErrorMessage = "Este campo deve ter entre 10 e 200 caracteres!")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Informe seu telefone, servirá como alternativa de contato além do e-mail!")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Diga-nos sua data de nascimento, isso nos fará saber sua idade e seu aniversário!" + @"\o/")]
        public string Nascimento { get; set; }

        [Required(ErrorMessage = "É de suma importância que você indique o tipo do cadastro!")]
        public string Tipo { get; set; }

        public long Rfid { get; set; }
    }
}
